package com.asl_emp_mng.app.screens.settings.dataClass

data class CompanyViewRequestDeviceResponse(
    val success: Boolean,
    val message: String,
    val approvedCount: Int,
    val rejectedCount: Int,
    val data: List<DeviceRequest>
)

data class DeviceRequest(
    val id: Int,
    val emp_id: String,
    val name: String,
    val company_id: Int,
    val branch_id: Int,
    val department_id: Int,
    val date_of_birth: String?,
    val gender: String?,
    val marital_status: String?,
    val blood_group: String?,
    val guardian_name: String?,
    val country: String?,
    val state: String?,
    val city: String?,
    val address: String?,
    val pin: String?,
    val date_of_joining: String?,
    val date_of_leaving: String?,
    val job_title_id: String?,
    val employee_type_id: String?,
    val official_email_id: String?,
    val esi_number: String?,
    val pf_number: String?,
    val privileged_leave: String?,
    val sick_leave: String?,
    val casual_leave: String?,
    val email: String,
    val image: String?,
    val resume: String?,
    val phone: String,
    val position: String,
    val salary: String,
    val geo_status: String?,
    val status: String?,
    val device_status: String,
    val created_at: String,
    val updated_at: String,
    val shift_id: String?,
    val device_id: String,
    val attendance_type: String?,
    val aadhar: String?,
    val pan: String?,
    val voter: String?,
    val driving_license: String?,
    val uan: String?,
    val aadhar_verify: String,
    val pan_verify: String,
    val voter_verify: String,
    val dl_verify: String,
    val uan_verify: String,
    val face_verify: String,
    val address_verify: String,
    val is_verified: String,
    val pan_response: String?,
    val aadhar_response: String?,
    val voter_response: String?,
    val dl_response: String?,
    val uan_response: String?,
    val face_response: String?,
    val address_response: String?
)



